### ISSUE TITLE
It can't find the function of pack_vectors in tenseal

### ISSUE THREAD

**Issue by sunshine-lh** [youben11/encrypted-evaluation#9]
Hello, I meet a problem when I run this program. This problem from server.py is that it can't find the function of pack_vectors in tenseal. In addition, I look other versions of tenseal, and I find that all of them have not the pack_vectors function. So, I want to get some solutions from you. Looking for your reply!

**Comment by youben11** [comment]
Sorry for seeing this too late maybe, but I guess it's just an API breaking change, you can update to latest version and use the latest API

**Comment by sunshine-lh** [comment]
Thanks for your reply!
The tenseal that I used is the latest version, but the question that it can't find the function of pack_vectors in tenseal&nbsp; still exists.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youben11/encrypted-evaluation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月22日(星期五) 凌晨0:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youben11/encrypted-evaluation] It can't find the function of pack_vectors in tenseal (#9)





 
Sorry for seeing this too late maybe, but I guess it's just an API breaking change, you can update to latest version and use the latest API
